name: Go CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Deploy to EC2
        env:
          EC2_KEY: ${{ secrets.EC2_PEM }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "${EC2_KEY}" > "deploy_key.pem"
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@ec2-13-60-89-35.eu-north-1.compute.amazonaws.com << EOF
            cd /home/ubuntu/unit-testing
            git pull origin master
            pkill -f app || true
            go build -o app
            nohup ./app > app.log 2>&1 &
            exit
          EOF
